controllers:
  glance:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      glance:
        image:
          repository: docker.io/glanceapp/glance
          tag: v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
        args:
          - --config
          - /config/glance.yml
        env:
          TZ: Europe/Zurich
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1022
    runAsGroup: 1022
    fsGroup: 1022
    fsGroupChangePolicy: OnRootMismatch
service:
  app:
    controller: glance
    ports:
      http:
        port: 8080
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: &host glance.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
persistence:
  config:
    type: configMap
    name: glance-config
