# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: backstage-secrets
    labels:
        app.kubernetes.io/name: backstage
type: Opaque
stringData:
    FRONTEND_URL: https://backstage.pitower.link
    BACKEND_URL: https://backstage.pitower.link
    GITHUB_CLIENT_ID: Ov23lie3kUTskm7X4j8g
    GITHUB_CLIENT_SECRET: cb10f0a526d613557aef260ef5055d18f518cc2f
    AUTH_ORG_APP_ID: "933604"
    AUTH_ORG_CLIENT_ID: Iv23liDrsT18q7brhRhN
    AUTH_ORG_CLIENT_SECRET: f2a20e4202f0733ea9f32eb412359deae9e4beec
    AUTH_ORG_WEBHOOK_SECRET: 6966d81b4282444f92b637ac3a6465db266da23e
    AUTH_ORG_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEogIBAAKCAQEAscyoNgSQnq32aqS1mtZimnfNx0AJ2qwPNXAu4xeEvZQx+x9G
        cwfty+czZd7Xsybwt/5WxjlPTLqvMfnIzs3lYn8pXelik9ghmtUzHk28vxyEzMwz
        aFdRyHJhSH6IzU0R0tN8Mi3Q4Q08iHWztpMSMr1oOY2C1JKoopr/sxMEJbA1GNjU
        fhd4k7rXA11C/WNgIJFWycRYlJeECQDaAIFduElYfdl/6iFCMAEPF/vVd1QvQN42
        9Nv8s9+NqNWovIT5KrJfLyWRV/bKpQlD+OqP4cJ6xLOC8NEBj48GPD9v0rvvc1Ur
        NQ8GJb+0ByJwQ9vtSdbA3SnjftEtaLTC6aD0ZQIDAQABAoIBAHoblPasQepIjTCG
        eBaj38o4N0H9MAdXHYbUyc66qzZL3duaihacPmtIGJuA5OCsAKxMZ6nxWA3ZNFL9
        OjUVYNE5hd5yV3oz+DhO7bGFL/iMjIPeRfwF5CvmqftQs4FTycbh6azInGjDX2xU
        cZ0U+m2QeVD1aAG3y0sJakzA5Zs/d5RyUe3mM8LwEgV3B616Tvn50iGAimg8aqnK
        IZ/28Dj6vue7+/sOy4KXEiQy3ZC084oGdHpdmpAL3kkf+OsflJ9OgAnLV1238dyG
        9nQIW+1lpi7ojA5Qaxhy8vaJOryHfXnWSGCmk7u+XSf55BamHu2ikt8O9r7ha0VQ
        8xYCBaECgYEA6j8Io+E80fkFSmvYgTrZq97VvIs5vrQvO9RVh4AVKWQ9PVQ5CbNA
        x16ug82qzwoINoitHdjie2zbQGzcz3PwuMhtZo/GpcTLkn5XNlcxzWmxxqd8IVmo
        71c+OJwnoVKoex4BskDzrDQI0iEm0jeeEnVObllb3bsrHo9c0RifFHkCgYEAwk+o
        iGKFED39CHfSCRk2sFYXJuaK2hNUrsE1g+S+5zs2+a/9OwnsEufsGQzfJugMAAFx
        wl9BK8rhEeNoGGIEgC8bfn/I16CqAeScTDbN73Ru5SaXXi8tEYELbt1ay6EdZvt3
        dp3C55WeJZ7YjVErmAX0ymFwuMUh2d59XK2bLE0CgYAl+uZpu+Fioh+re2T1Pxd/
        +HdrRJ+uPgTSjJD5kVjdBzWutfMxkXDVYpKlKDmjrBq8zNhU2I+QN4wtG/mJYWEM
        dOLYGEO7KPdg3z9Avk6C4bpDXXCQ77qmY9zgzODYFVDf9XOM9V8M8rrjZyCmQQJO
        N9rppW9xuiE5qUEBXh6c8QKBgDUlXn43HBfuLHgVdbAhYlDmqxxrsAynfuDxXXa+
        qOxLyOSQGx37v8MIBg5v89ULYMTboEa+kO+uZNLktQL+RCbfO5Dk2IUJn5Y29fzu
        fHMDEJXCcWJEWvpPplXjW0MYxRb2rp0V10pKJOA7SxWT3u2Mq4BzGEahPHn/naAs
        p6V9AoGAQJWp6xAOsyQkt5VMnxhISB/+i7Y6ZBpHKf2uoXveqV159F6yinf2UDse
        UM/BFHgPdXNe1OL7GEO+TKMdblW0mKRVxkl0c7krZ7PQj3Gp2U2++THp2WIVApyD
        5PuLddO3uRAO95qdNfSGWar24BKs5PHel8a4gXQla7Sax0AsgK8=
        -----END RSA PRIVATE KEY-----
