controllers:
  n8n:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      app:
        image:
          repository: ghcr.io/n8n-io/n8n
          tag: 1.101.1
        env:
          DB_SQLITE_VACUUM_ON_STARTUP: true
          EXECUTIONS_DATA_PRUNE: true
          EXECUTIONS_DATA_MAX_AGE: 7
          EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
          GENERIC_TIMEZONE: "Europe/Zurich"
          N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
          N8N_PROTOCOL: "https"
          N8N_PORT: &port 8080
          N8N_HOST: &hostName n8n.pitower.link
          N8N_LOG_LEVEL: info
          N8N_LOG_OUTPUT: console
          # N8N_ENCRYPTION_KEY:
          #   valueFrom:
          #     secretKeyRef:
          #       name: n8n-secret
          #       key: N8N_ENCRYPTION_KEY
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            memory: 2Gi

service:
  app:
    controller: n8n
    ports:
      http:
        port: *port

persistence:
  data:
    existingClaim: n8n
    advancedMounts:
      n8n:
        app:
          - path: /home/node/.n8n
ingress:
  app:
    enabled: true
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: n8n.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: *port
    tls:
      - hosts:
          - echo.pitower.link
  webhooks:
    enabled: true
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: n8n-webhook.pitower.link
        paths:
          - path: /webhook
            service:
              identifier: app
              port: *port
# route:
#   app:
#     hostnames:
#       - *hostName
#     parentRefs:
#       - name: internal
#         namespace: kube-system
#         sectionName: https
#     rules:
#       - backendRefs:
#           - identifier: app
#             port: *port
#   webhooks:
#     hostnames:
#       - n8n-webhook.pitower.link
#     parentRefs:
#       - name: external
#         namespace: kube-system
#         sectionName: https
#     rules:
#       - matches:
#           - path:
#               value: /webhook
#         backendRefs:
#           - identifier: app
#             port: *port
