controllers:
  jellyfin:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: "worker-04"
    containers:
      app:
        image:
          repository: ghcr.io/jellyfin/jellyfin
          tag: 10.10.7@sha256:e4d1dc5374344446a3a78e43dd211247f22afba84ea2e5a13cbe1a94e1ff2141
        env:
          DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
        resources:
          requests:
            cpu: 100m
            gpu.intel.com/i915: 1
            memory: 1024M
          limits:
            gpu.intel.com/i915: 1
            memory: 8192M
service:
  app:
    controller: jellyfin
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: jellyfin.pitower.link
      io.cilium/lb-ipam-ips: "192.168.0.229"
    ports:
      http:
        port: 8096

ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: &host jellyfin.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host

persistence:
  config:
    existingClaim: jellyfin
    globalMounts:
      - path: /config
  config-cache:
    existingClaim: jellyfin-cache
    globalMounts:
      - path: /config/metadata
  media:
    type: nfs
    server: data
    path: /volume1/media
    advancedMounts:
      jellyfin:
        app:
          - path: /data/nas-media
  tmpfs:
    type: emptyDir
    advancedMounts:
      jellyfin:
        app:
          - path: /cache
            subPath: cache
          - path: /config/log
            subPath: log
          - path: /tmp
            subPath: tmp
  # quicksync:
  #   type: hostPath
  #   hostPath: /dev/dri
  #   hostPathType: Directory
  #   advancedMounts:
  #     jellyfin:
  #       app:
  #         - path: /dev/dri
