---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 2.0.0
    releaseName: onepassword-connect
    namespace: security
    valuesFile: values.yaml
    includeCRDs: true
