---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.50.0
    releaseName: fluent-bit
    valuesFile: values.yaml
    namespace: monitoring